apiVersion: v1
kind: Service
metadata:
  name: analytics-ui
  namespace: staging
spec:
  selector:
    app: analytics-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
