apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-ui
  labels:
    app: analytics-ui
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: analytics-ui
    spec:
      containers:
        - image: nginx:1.24.0  # Different version for staging
          imagePullPolicy: Always
          name: analytics-ui
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
